finally US06 is done and polished
ersuamine/Fleet_Management pull request #23
Opened 2024-07-18 14:35 UTC by dilovar1992

2024-07-18 14:53 UTC, ersuamine commented on src/test/resources/features/US06_editCarInfoItems_TD.feature
>      And user hover over three dots on the end of the list of records in sales and store page
Hover over elipses

2024-07-18 14:56 UTC, ersuamine commented on src/test/java/com/fleet_management/step_definitions/US06_EditCarInfoItems_stepDef_TD.java
>      Actions actions = new Actions(Driver.getDriver());
Initialize actions here but create at method level.

2024-07-18 14:59 UTC, ersuamine requested changes

2024-07-18 14:59 UTC, ersuamine commented on src/test/java/com/fleet_management/step_definitions/US06_EditCarInfoItems_stepDef_TD.java
> +    @When("user chooses {string} from  the {string} module")
This is a repetitive step definition, use the one from US05

2024-07-19 07:03 UTC, ersuamine approved these changes

2024-07-19 14:14 UTC, 4745Mthn approved these changes

2024-07-19 14:15 UTC, merged