Metehan
ersuamine/Fleet_Management pull request #27
Opened 2024-07-19 16:58 UTC by 4745Mthn

2024-07-19 16:59 UTC, dilovar1992 approved these changes

2024-07-19 17:01 UTC, dilovar1992 approved these changes

2024-07-19 18:06 UTC, ersuamine requested changes

2024-07-19 18:06 UTC, ersuamine commented on src/test/resources/features/US08_CreateCalendarEvent_MA.feature
>    @Ac1
Can you change feature description "Feature: Users should be able to login" on line 2
It should be describing your feature

2024-07-19 18:06 UTC, ersuamine commented on src/test/resources/features/US01_DashboardModules_MA.feature
>  Feature: Users should be able to login
Please revise with more appropriate feature description

2024-07-19 18:06 UTC, ersuamine commented on src/test/java/com/fleet_management/step_definitions/US08_CreateCalendarEvent_StepDef_MA.java
> +        Assert.assertTrue(expectedWarningMessage.contains(calendarEventsPage.warningMessage.getText()));
Should expected contain the actual, or the actual should contain the expected

2024-07-20 15:29 UTC, ersuamine approved these changes
Thank you for your hard work

2024-07-20 15:30 UTC, merged